management:
  endpoints:
    web:
      exposure:
        include: "*"  #health,info,metrics,env
  endpoint:
    health:
      show-details: "always"  # Show detailed health info
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tenant_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: utp_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Cognos Environment Manager API base URL  Example : https://<cognos_analytics_server>:<port>/api/v1
cognos.api.url: https://ap1.ca.analytics.ibm.com/api/v1

cognos.api.base-url: https://ap1.ca.analytics.ibm.com
cognos.api.auth-token : Bearer YOUR_API_TOKEN
cognos.api.cam-token : MTsxMDE6OTRiNmNkMDctMTJlOS0wNjEzLWQ0NzYtODI1NjRhMGEwMjA2OjM2NjMxNzI4MDE7MDszOzA7
cognos.api.xsrf-token : vZVbnwbXxbCevKfCRSlE3joLdhProX6P
logging.level.root: INFO
spring.flyway.clean-on-validation-error: true

